### ISSUE TITLE
Qt 6 build crashes on file open

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD-snap#189]
The Qt 6 snap build works otherwise fine, but it crashes with this error when opening a new file, making it unusable:

```
(FreeCAD:51800): GLib-GIO-ERROR **: 15:50:06.800: No GSettings schemas are installed on the system
```

As mentioned on https://github.com/FreeCAD/FreeCAD-snap/pull/179#issuecomment-2809673327

## Other references to this issue

- Someone is adding the GNOME extension when facing this: https://forum.snapcraft.io/t/all-my-snaps-are-not-working-any-longer/24459/3
- Some other search results mention `GSETTINGS_SCHEMA_DIR` as well

**Comment by furgo16** [comment]
@ScarlettGatelyMoore have you had any luck with your tests from https://github.com/FreeCAD/FreeCAD-snap/pull/179#issuecomment-2810361863 ? Thanks!

**Comment by furgo16** [comment]
I hope you're doing better, thanks!

**Comment by furgo16** [comment]
@ScarlettGatelyMoore I hope you're well. Did you manage to do the build and testing? Is there anything I can do to help?

**Comment by ScarlettGatelyMoore** [comment]
Hi! Sorry, I had surgery a little over a week ago and was delayed. I am still working on this and hope to have something for you to test tomorrow. Thanks for your patience!

**Comment by ScarlettGatelyMoore** [comment]
I am happy to report this should be fixed, I have tested with one of ours and the crash is gone :) All pushed to stable, please rebuild and test!

**Comment by furgo16** [comment]
@ScarlettGatelyMoore thank you. Unfortunately, I cannot rebuild:

1. I just noticed our Qt6 snap builds started [failing last week](https://github.com/FreeCAD/FreeCAD-snap/actions/runs/14850073741/job/41691891512#step:3:11048) () (2025-05-06), with the error below:
2. The error is still present as of the daily build from last night, so rebuilding now with the error still present will fail

```
:: /snap/kde-qt6-core24-sdk/current/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpyside6.abi3.so.6.9.0: undefined reference to `QBasicMutex::destroyInternal(void*)@Qt_6'
```

Did the newly uploaded kde-qt6-core24-sdk break PySide?

**Comment by ScarlettGatelyMoore** [comment]
Looks like it succeeded?

**Comment by furgo16** [comment]
Unfortunately not. You need to look at the summary, Annotations section: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/15019807199 - it failed with the same error.

The GitHub CI job is set to continue on failure, so that internal logs can be written for debugging. But continuing on failure marks the job as succeeded. But that's just a GitHub thing.

**Comment by ScarlettGatelyMoore** [comment]
It seems neon moved to qt 6.9 hence the symbol error. I am only on 6.8.3. Ugh. Two options here, build pyside6 from source ( I haven't had much luck here ) or wait until I update to 6.9.

**Comment by furgo16** [comment]
Then I think it would be best to update to 6.9, as this is what worked the last time around. Is there a way to keep PySide in sync with the rest of the kde-neon-6 snaps, so that we don't end up in this situation next time around? Thanks!

**Comment by ScarlettGatelyMoore** [comment]
Yes, I really need to make a pyside snap. Time is an issue. This is all freetime work for me. Enough work to be a full time job though.

**Comment by ScarlettGatelyMoore** [comment]
I was asked to hold off on qt 6.9 as it is a major release and could break things for another project that is in review with Canonical. So it looks like pyside snap is in order.

**Comment by furgo16** [comment]
@ScarlettGatelyMoore I hope you're well! We're about to switch the FreeCAD upstream builds to Qt6. We've never been able to release the snap's Qt 6 build, as is currently blocked on this issue.

I don't have insight or experience on the KDE builds, but I'd like to see if there is anything we can do on our side to make progress on this, without putting more work on your plate. Do you have any suggestions? Thanks!

**Comment by furgo16** [comment]
> If you want to try to build pyside from source here,

Thanks. I would appreciate some guidance here, as I don't know where this snap should be uploaded to. You mentioned a while back you had started it but it didn't build. Do you have that preliminar snap work available somewhere, so that it gives us a head start?

**Comment by ScarlettGatelyMoore** [comment]
> > If you want to try to build pyside from source here,
> 
> Thanks. I would appreciate some guidance here, as I don't know where this snap should be uploaded to. You mentioned a while back you had started it but it didn't build. Do you have that preliminar snap work available somewhere, so that it gives us a head start?

No need to upload it, just create a part in your snapcraft.yaml
You will likely need to adjust the env to fit yours
If you get it to build, I will borrow your work and create a standalone snap from it. I just don't have time, trying to catch up financially after having a broken arm for a year. Sorry.

  pyside6:
    source: https://code.qt.io/pyside/pyside-setup.git
    source-tag: $CRAFT_PROJECT_VERSION
    plugin: cmake
    build-packages:
      - libgl-dev
      - python3-dev
      - python3.12-dev
      - libpython3.12-dev
      - libclang-18-dev
      - python3-setuptools
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE"
      - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr"
    build-environment: &buildenvironment
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin${PATH:+:$PATH}
      - PKG_CONFIG_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kde-qt6-core24-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
      - XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kde-qt6-core24-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
      - LD_LIBRARY_PATH: "$CRAFT_STAGE/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy:$CRAFT_STAGE/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      - PYTHONPATH: ${CRAFT_STAGE}/usr/lib/python3.12/site-packages:${CRAFT_STAGE}/usr/lib/python3/dist-packages
      - C_INCLUDE_PATH: ${CRAFT_STAGE}/usr/include/python3.12${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}
      - CPATH:  ${CRAFT_STAGE}/usr/include/python3.12${CPATH:+:$CPATH}

**Comment by ScarlettGatelyMoore** [comment]
source-tag: $CRAFT_PROJECT_VERSION needs to be 6.8.3

**Comment by furgo16** [comment]
Thank you!

**Comment by furgo16** [comment]
No worries, all the best!

**Comment by furgo16** [comment]
Remaining issues filed at https://github.com/FreeCAD/FreeCAD-snap/issues/220
